import NavBar from '@/components/NavBar'
import './globals.css'

export const metadata = {
  title: 'Blog Practice',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={'dark:bg-slate-700 text-white'}>
        <NavBar />
        {children}      
      </body>
    </html>
  )
}
